# Generated by Django 4.2.7 on 2023-11-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='translator',
            old_name='user_id',
            new_name='user',
        ),
    ]
