# Generated by Django 4.2.7 on 2023-11-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_user_id_editor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
