# Generated by Django 4.2.7 on 2023-11-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_project_finished_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approve',
            old_name='editor_id',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='approve',
            old_name='pages_per_day_id',
            new_name='pages_per_day',
        ),
        migrations.RenameField(
            model_name='disapprove',
            old_name='editor_id',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='disapprove',
            old_name='pages_per_day_id',
            new_name='pages_per_day',
        ),
        migrations.RenameField(
            model_name='pages_per_day',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='pages_per_day',
            old_name='translator_id',
            new_name='translator',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project_editor',
            old_name='editor_id',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='project_editor',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project_translator',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project_translator',
            old_name='translator_id',
            new_name='translator',
        ),
    ]
