# Generated by Django 4.2.7 on 2023-11-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_editor_id_approve_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_editor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_translator',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_translator',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='translator',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
