# Generated by Django 4.2.7 on 2023-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_editor_active_manager_active_project_editor_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.CharField(default='https://i.ytimg.com/vi/jYFk1O_t43A/maxresdefault.jpg', max_length=500),
        ),
    ]
