# Generated by Django 4.2.7 on 2023-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_user_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(blank=True, default='https://i.ytimg.com/vi/jYFk1O_t43A/maxresdefault.jpg', max_length=500, null=True),
        ),
    ]
