# Generated by Django 4.2.7 on 2023-11-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_approve_pages_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='pages_per_day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pages_per_day'),
        ),
        migrations.AlterField(
            model_name='disapprove',
            name='pages_per_day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pages_per_day'),
        ),
    ]
