# Generated by Django 4.2.7 on 2023-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_approve_pages_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_per_day',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
