# Generated by Django 4.2.7 on 2023-11-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_pages_per_day_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_per_day',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
