# Generated by Django 4.2.7 on 2023-11-18 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_pages_per_day_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_per_day',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
