# Generated by Django 4.2.7 on 2023-11-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_pages_per_day_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disapprove',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pages_per_day',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
