# Generated by Django 4.2.7 on 2023-11-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_project_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
    ]
